version: 3

project:
  id: onchain-bridge-dispenser
  name: Private Dispenser
  policy: policy-1
  url: https://github.com/bass-dev-core/onchain-bridge-dispenser

analyze:
  modules:
    - name: frontend
      type: npm
      target: frontend
      path: frontend

  notices:
    - file: NOTICE.md
