version: 3

project:
  id: git+github.com/whonion/onchain-bridge-dispenser
  name: onchain-bridge-dispenser
  url: https://github.com/whonion/onchain-bridge-dispenser

paths:
  exclude:
    - .git
    - node_modules
    - dist
    - build

license:
  policy: notice
  files:
    - LICENSE
    - LICENSE.MPL-2.0
    - NOTICE.md

  dependencies:
    '@vercel/og':
      license: MPL-2.0
      files:
        - LICENSE.MPL-2.0
    'satori':
      license: MPL-2.0
      files:
        - LICENSE.MPL-2.0
