name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0

      - name: Install frontend dependencies
        run: npm i
        working-directory: ./frontend

      - name: Lint (frontend)
        run: npm run lint
        working-directory: ./frontend

      - name: Build (frontend)
        run: npm run build
        working-directory: ./frontend
